import json, os

TOKEN = "3EqzK9BvXDwGI3rgFQ9jMvnSFY7_6Nvp6CF6e8oAmK64Kc9Bp"

nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.12.0"},
        "colab": {"provenance": []},
        "accelerator": "GPU",
        "gpuClass": "standard"
    },
    "cells": []
}


def code_cell(cid, src):
    return {"cell_type": "code", "execution_count": None, "id": cid,
            "metadata": {}, "outputs": [], "source": src}


def md_cell(cid, src):
    return {"cell_type": "markdown", "id": cid, "metadata": {}, "source": src}


# ── TITLE
nb["cells"].append(md_cell("md-title", (
    "# IR Project — Complete Google Colab Notebook\n\n"
    "> Enable GPU: Runtime -> Change runtime type -> T4 GPU\n\n"
    "| Cell | Purpose |\n|---|---|\n"
    "| 1 | Download & Extract |\n"
    "| 2 | Install libraries |\n"
    "| 3 | Set Python path |\n"
    "| 4 | NLTK data |\n"
    "| 5 | Create topic_service + Start 7 services |\n"
    "| 5b | ngrok public URL |\n"
    "| 6 | Health check |\n"
    "| 7 | Load Quora dataset |\n"
    "| 8 | Build search indexes |\n"
    "| 9 | Build LDA topic model (NEW) |\n"
    "| 10 | View all topics (NEW) |\n"
    "| 11 | Search with topic labels (NEW) |\n"
    "| 12 | Regular search |\n"
    "| 13 | Compare 6 models |\n"
    "| 14 | Evaluate MAP/nDCG |\n"
    "| 15 | Debug logs |\n"
    "| 16 | Save to Drive |\n"
    "| 16b | Restore from Drive |"
)))

# ── CELL 1
nb["cells"].append(code_cell("cell-01", "\n".join([
    "# CELL 1 — Download & Extract from Google Drive",
    "!pip install -q gdown",
    "import gdown, zipfile, os",
    "",
    "FILE_ID   = '1ZLIdrsobW4nA6Lu02h5ZdY5NwO6OjPdD'",
    "ZIP_PATH  = '/content/IR_Project.zip'",
    "PROJ_PATH = '/content/IR_Project'",
    "",
    "gdown.download(id=FILE_ID, output=ZIP_PATH, quiet=False)",
    "with zipfile.ZipFile(ZIP_PATH, 'r') as z:",
    "    z.extractall(PROJ_PATH)",
    "print('Done! Contents:', os.listdir(PROJ_PATH))",
])))

# ── CELL 2
nb["cells"].append(code_cell("cell-02", "\n".join([
    "# CELL 2 — Install Libraries (~2-3 min)",
    "import subprocess",
    "subprocess.run(['pip', 'install', '-q',",
    "    'fastapi>=0.111.0', 'uvicorn[standard]>=0.29.0', 'httpx>=0.27.0',",
    "    'pydantic>=2.0.0', 'nltk>=3.8.1', 'pyspellchecker>=0.8.1',",
    "    'ir-datasets>=0.5.5', 'scikit-learn>=1.4.0', 'rank-bm25>=0.2.2',",
    "    'scipy>=1.13.0', 'numpy>=1.26.0', 'gensim>=4.3.0',",
    "    'sentence-transformers>=2.7.0', 'pyngrok'])",
    "print('All packages installed!')",
])))

# ── CELL 3
nb["cells"].append(code_cell("cell-03", "\n".join([
    "# CELL 3 — Set Python Path",
    "import sys, os",
    "",
    "PROJ_PATH = '/content/IR_Project'",
    "BACKEND_PATH = None",
    "for root, dirs, files in os.walk(PROJ_PATH):",
    "    if 'backend_services' in dirs:",
    "        BACKEND_PATH = os.path.join(root, 'backend_services')",
    "        break",
    "if BACKEND_PATH is None:",
    "    BACKEND_PATH = PROJ_PATH + '/backend_services'",
    "sys.path.insert(0, BACKEND_PATH)",
    "print('Backend path:', BACKEND_PATH)",
    "svcs = [d for d in os.listdir(BACKEND_PATH) if os.path.isdir(os.path.join(BACKEND_PATH, d)) and not d.startswith('_')]",
    "print('Services found:', svcs)",
])))

# ── CELL 4
nb["cells"].append(code_cell("cell-04", "\n".join([
    "# CELL 4 — NLTK Data",
    "import nltk",
    "for pkg in ['punkt_tab', 'stopwords', 'wordnet', 'averaged_perceptron_tagger_eng', 'omw-1.4']:",
    "    nltk.download(pkg, quiet=True)",
    "    print('  OK:', pkg)",
    "print('NLTK ready!')",
])))

# ── CELL 5 — big cell with topic_service creation
cell5_lines = [
    "# CELL 5 — Create topic_service + Start ALL 7 Services",
    "import os, subprocess, time",
    "",
    "# Fix data directories",
    "data_base = os.path.normpath(os.path.join(BACKEND_PATH, '..', 'data'))",
    "os.makedirs(os.path.join(data_base, 'quora', 'word2vec'), exist_ok=True)",
    "os.makedirs(os.path.join(data_base, 'quora', 'bert'), exist_ok=True)",
    "print('Data folders ready')",
    "",
    "# Create topic_service package",
    "topic_dir = os.path.join(BACKEND_PATH, 'topic_service')",
    "os.makedirs(topic_dir, exist_ok=True)",
    "",
    "# __init__.py",
    "open(os.path.join(topic_dir, '__init__.py'), 'w').write('\"\"\"Topic Detection Service.\"\"\"\\n')",
    "",
    "# schemas.py",
    "schemas_code = '''from pydantic import BaseModel, Field",
    "from typing import Optional",
    "class BuildTopicsRequest(BaseModel):",
    "    dataset_name: str",
    "    num_topics: int = Field(10, ge=2, le=50)",
    "    num_top_words: int = Field(8, ge=3, le=20)",
    "class TopicDefinition(BaseModel):",
    "    topic_id: int",
    "    label: str",
    "    top_words: list[str]",
    "    doc_count: int",
    "class BuildTopicsResponse(BaseModel):",
    "    dataset: str",
    "    status: str",
    "    num_topics: int",
    "    topics: list[TopicDefinition] = []",
    "    error: Optional[str] = None",
    "class DocTopicRequest(BaseModel):",
    "    doc_ids: list[str]",
    "    dataset_name: str",
    "class DocTopicResult(BaseModel):",
    "    doc_id: str",
    "    topic_id: int",
    "    topic_label: str",
    "    top_words: list[str]",
    "    probability: float",
    "class DocTopicResponse(BaseModel):",
    "    dataset: str",
    "    results: list[DocTopicResult]",
    "class TopicStatusResponse(BaseModel):",
    "    dataset: str",
    "    status: str",
    "    num_topics: int = 0",
    "    error: Optional[str] = None",
    "'''",
    "open(os.path.join(topic_dir, 'schemas.py'), 'w').write(schemas_code)",
    "",
    "# lda_model.py",
    "lda_code = '''import logging, pickle",
    "from pathlib import Path",
    "import numpy as np",
    "from sklearn.decomposition import LatentDirichletAllocation",
    "from sklearn.feature_extraction.text import CountVectorizer",
    "logger = logging.getLogger(\"topic_service.lda\")",
    "def _tok(t): return t.split()",
    "class LDAModel:",
    "    def __init__(self):",
    "        self._lda = self._vec = None",
    "        self._topics = []",
    "        self._map = {}",
    "        self._n = 0",
    "    def build(self, documents, num_topics=10, num_top_words=8):",
    "        self._n = num_topics",
    "        corpus = [d.get(\"cleaned\", \" \".join(d.get(\"tokens\", []))) for d in documents]",
    "        self._vec = CountVectorizer(tokenizer=_tok, preprocessor=None, lowercase=False,",
    "            token_pattern=None, max_df=0.95, min_df=5, max_features=20_000)",
    "        dtm = self._vec.fit_transform(corpus)",
    "        self._lda = LatentDirichletAllocation(n_components=num_topics, max_iter=15,",
    "            learning_method=\"online\", batch_size=512, random_state=42, n_jobs=-1)",
    "        mat = self._lda.fit_transform(dtm)",
    "        tids = np.argmax(mat, axis=1).tolist()",
    "        probs = mat.max(axis=1).tolist()",
    "        fn = self._vec.get_feature_names_out()",
    "        counts = [0] * num_topics",
    "        for t in tids: counts[t] += 1",
    "        self._topics = []",
    "        for i, dist in enumerate(self._lda.components_):",
    "            idx = dist.argsort()[-num_top_words:][::-1]",
    "            words = [fn[j] for j in idx]",
    "            self._topics.append({\"topic_id\": i, \"label\": \"/\".join(words[:3]),",
    "                \"top_words\": words, \"doc_count\": counts[i]})",
    "        self._map = {}",
    "        doc_ids = [d[\"doc_id\"] for d in documents]",
    "        for i, did in enumerate(doc_ids):",
    "            t = self._topics[tids[i]]",
    "            self._map[did] = {\"topic_id\": t[\"topic_id\"], \"topic_label\": t[\"label\"],",
    "                \"top_words\": t[\"top_words\"], \"probability\": round(float(probs[i]), 4)}",
    "        logger.info(f\"LDA done: {num_topics} topics, {len(self._map)} docs\")",
    "    def get_doc_topic(self, doc_id): return self._map.get(doc_id)",
    "    def get_all_topics(self): return self._topics",
    "    def infer_topic(self, text):",
    "        v = self._vec.transform([text])",
    "        d = self._lda.transform(v)[0]",
    "        i = int(np.argmax(d))",
    "        t = self._topics[i]",
    "        return {\"topic_id\": i, \"topic_label\": t[\"label\"],",
    "            \"top_words\": t[\"top_words\"], \"probability\": round(float(d[i]), 4)}",
    "    @property",
    "    def num_topics(self): return self._n",
    "    @property",
    "    def is_built(self): return self._lda is not None",
    "    def save(self, path):",
    "        p = Path(path)",
    "        p.parent.mkdir(parents=True, exist_ok=True)",
    "        with open(p, \"wb\") as f:",
    "            pickle.dump({\"lda\": self._lda, \"vec\": self._vec,",
    "                \"topics\": self._topics, \"map\": self._map, \"n\": self._n}, f)",
    "    def load(self, path):",
    "        p = Path(path)",
    "        if not p.exists(): return False",
    "        with open(p, \"rb\") as f: data = pickle.load(f)",
    "        self._lda = data[\"lda\"]; self._vec = data[\"vec\"]",
    "        self._topics = data[\"topics\"]; self._map = data[\"map\"]; self._n = data[\"n\"]",
    "        logger.info(f\"LDA loaded from {p} ({self._n} topics)\")",
    "        return True",
    "'''",
    "open(os.path.join(topic_dir, 'lda_model.py'), 'w').write(lda_code)",
    "",
    "# main.py",
    "main_code = '''import logging, threading",
    "from contextlib import asynccontextmanager",
    "from pathlib import Path",
    "import httpx",
    "from fastapi import FastAPI, HTTPException, BackgroundTasks, Query",
    "from fastapi.middleware.cors import CORSMiddleware",
    "from topic_service.lda_model import LDAModel",
    "from topic_service.schemas import (BuildTopicsRequest, BuildTopicsResponse,",
    "    DocTopicRequest, DocTopicResponse, DocTopicResult, TopicStatusResponse)",
    "logger = logging.getLogger(\"topic_service\")",
    "logging.basicConfig(level=logging.INFO, format=\"%(asctime)s|%(levelname)s|%(message)s\")",
    "PREP = \"http://localhost:8001\"",
    "DATA = Path(__file__).resolve().parent.parent.parent / \"data\"",
    "class State:",
    "    def __init__(self, n):",
    "        self.name = n; self.status = \"not_built\"; self.error = None",
    "        self.model = LDAModel(); self._lock = threading.Lock()",
    "_states = {}; _lock = threading.Lock()",
    "def _get(n):",
    "    with _lock:",
    "        if n not in _states: _states[n] = State(n)",
    "        return _states[n]",
    "@asynccontextmanager",
    "async def lifespan(app):",
    "    if DATA.exists():",
    "        for d in DATA.iterdir():",
    "            if d.is_dir():",
    "                s = _get(d.name)",
    "                if s.model.load(d / \"lda_model.pkl\"):",
    "                    with s._lock: s.status = \"ready\"",
    "    logger.info(\"Topic Service ready.\")",
    "    yield",
    "app = FastAPI(title=\"Topic Detection Service\", lifespan=lifespan)",
    "app.add_middleware(CORSMiddleware, allow_origins=[\"*\"], allow_methods=[\"*\"], allow_headers=[\"*\"])",
    "@app.get(\"/health\")",
    "def health(): return {\"status\": \"ok\", \"service\": \"topic_detection\"}",
    "@app.post(\"/topics/build\", response_model=BuildTopicsResponse)",
    "def build(req: BuildTopicsRequest, bg: BackgroundTasks):",
    "    s = _get(req.dataset_name)",
    "    if s.status == \"building\": raise HTTPException(409, \"Already building.\")",
    "    bg.add_task(_pipeline, s, req)",
    "    return BuildTopicsResponse(dataset=req.dataset_name, status=\"building\", num_topics=req.num_topics)",
    "@app.get(\"/topics/status\", response_model=TopicStatusResponse)",
    "def tstatus(dataset_name: str = Query(...)):",
    "    s = _get(dataset_name)",
    "    with s._lock:",
    "        return TopicStatusResponse(dataset=dataset_name, status=s.status,",
    "            num_topics=s.model.num_topics, error=s.error)",
    "@app.get(\"/topics/all\")",
    "def all_topics(dataset_name: str = Query(...)):",
    "    s = _get(dataset_name)",
    "    if s.status != \"ready\": raise HTTPException(404, \"Not ready.\")",
    "    return {\"dataset\": dataset_name, \"num_topics\": s.model.num_topics, \"topics\": s.model.get_all_topics()}",
    "@app.post(\"/topics/detect\", response_model=DocTopicResponse)",
    "def detect(req: DocTopicRequest):",
    "    s = _get(req.dataset_name)",
    "    if s.status != \"ready\": raise HTTPException(404, \"Build topics first.\")",
    "    results = []",
    "    for did in req.doc_ids:",
    "        info = s.model.get_doc_topic(did)",
    "        if info:",
    "            results.append(DocTopicResult(doc_id=did, topic_id=info[\"topic_id\"],",
    "                topic_label=info[\"topic_label\"], top_words=info[\"top_words\"],",
    "                probability=info[\"probability\"]))",
    "        else:",
    "            results.append(DocTopicResult(doc_id=did, topic_id=-1,",
    "                topic_label=\"unknown\", top_words=[], probability=0.0))",
    "    return DocTopicResponse(dataset=req.dataset_name, results=results)",
    "@app.get(\"/topics/infer\")",
    "def infer(dataset_name: str = Query(...), text: str = Query(...)):",
    "    s = _get(dataset_name)",
    "    if s.status != \"ready\": raise HTTPException(404, \"Not ready.\")",
    "    return {\"dataset\": dataset_name, \"topic\": s.model.infer_topic(text)}",
    "def _pipeline(state, req):",
    "    with state._lock: state.status = \"building\"; state.error = None",
    "    try:",
    "        docs = _fetch(req.dataset_name)",
    "        state.model.build(docs, num_topics=req.num_topics, num_top_words=req.num_top_words)",
    "        d = DATA / req.dataset_name; d.mkdir(parents=True, exist_ok=True)",
    "        state.model.save(d / \"lda_model.pkl\")",
    "        with state._lock: state.status = \"ready\"",
    "        logger.info(f\"{req.dataset_name} LDA ready.\")",
    "    except Exception as e:",
    "        logger.exception(e)",
    "        with state._lock: state.status = \"error\"; state.error = str(e)",
    "def _fetch(name):",
    "    docs = []; off = 0",
    "    with httpx.Client(timeout=120) as c:",
    "        while True:",
    "            r = c.get(f\"{PREP}/dataset/docs\",",
    "                params={\"dataset_name\": name, \"offset\": off, \"limit\": 5000})",
    "            r.raise_for_status()",
    "            batch = r.json().get(\"documents\", [])",
    "            if not batch: break",
    "            docs.extend(batch); off += len(batch)",
    "            logger.info(f\"Fetched {len(docs)} docs...\")",
    "    return docs",
    "'''",
    "open(os.path.join(topic_dir, 'main.py'), 'w').write(main_code)",
    "",
    "print('topic_service created:', os.listdir(topic_dir))",
    "",
    "# Kill old and start 7 services",
    "os.system('fuser -k 8000/tcp 8001/tcp 8002/tcp 8003/tcp 8004/tcp 8005/tcp 8006/tcp 2>/dev/null')",
    "time.sleep(3)",
    "",
    "services = [",
    "    {'name': 'Preprocessing',   'port': 8001, 'module': 'preprocessing_service.main:app'},",
    "    {'name': 'Indexing',        'port': 8002, 'module': 'indexing_service.main:app'},",
    "    {'name': 'Retrieval',       'port': 8003, 'module': 'retrieval_service.main:app'},",
    "    {'name': 'Evaluation',      'port': 8004, 'module': 'ranking_eval_service.main:app'},",
    "    {'name': 'Refinement',      'port': 8005, 'module': 'query_refinement_service.main:app'},",
    "    {'name': 'Topic',           'port': 8006, 'module': 'topic_service.main:app'},",
    "    {'name': 'API Gateway',     'port': 8000, 'module': 'api_gateway.main:app'},",
    "]",
    "processes = []",
    "for svc in services:",
    "    log = open(f'/content/log_{svc[\"name\"]}.txt', 'w')",
    "    proc = subprocess.Popen(",
    "        ['uvicorn', svc['module'], '--host', '0.0.0.0',",
    "         '--port', str(svc['port']), '--log-level', 'warning'],",
    "        cwd=BACKEND_PATH, stdout=log, stderr=log)",
    "    processes.append(proc)",
    "    print(f'  Started {svc[\"name\"]:20} port={svc[\"port\"]} PID={proc.pid}')",
    "    time.sleep(3)",
    "",
    "print('Waiting 15s...')",
    "time.sleep(15)",
    "print('All 7 services launched!')",
]
nb["cells"].append(code_cell("cell-05", "\n".join(cell5_lines)))

# ── CELL 5b — ngrok
nb["cells"].append(code_cell("cell-05b", "\n".join([
    "# CELL 5b — ngrok Public URL",
    "from pyngrok import ngrok",
    "",
    f"NGROK_TOKEN = '{TOKEN}'",
    "",
    "ngrok.kill()",
    "ngrok.set_auth_token(NGROK_TOKEN)",
    "tunnel = ngrok.connect(8000)",
    "PUBLIC_URL = tunnel.public_url",
    "",
    "print('=' * 55)",
    "print(f'  API URL  : {PUBLIC_URL}')",
    "print(f'  API Docs : {PUBLIC_URL}/docs')",
    "print('=' * 55)",
])))

# ── CELL 6
nb["cells"].append(code_cell("cell-06", "\n".join([
    "# CELL 6 — Health Check",
    "import httpx",
    "",
    "checks = {",
    "    'Preprocessing  (8001)': 'http://localhost:8001/health',",
    "    'Indexing       (8002)': 'http://localhost:8002/health',",
    "    'Retrieval      (8003)': 'http://localhost:8003/health',",
    "    'Evaluation     (8004)': 'http://localhost:8004/health',",
    "    'Refinement     (8005)': 'http://localhost:8005/health',",
    "    'Topic Detect   (8006)': 'http://localhost:8006/health',",
    "    'API Gateway    (8000)': 'http://localhost:8000/health',",
    "}",
    "",
    "print('Health Check:')",
    "all_ok = True",
    "for name, url in checks.items():",
    "    try:",
    "        r = httpx.get(url, timeout=5)",
    "        ok = r.status_code == 200",
    "        status_icon = 'OK  ' if ok else 'WARN'",
    "        print(f'  {status_icon}  {name}')",
    "        if not ok: all_ok = False",
    "    except:",
    "        print(f'  FAIL  {name}')",
    "        all_ok = False",
    "",
    "print()",
    "if all_ok: print('All 7 services healthy!')",
    "else: print('Some not ready. Wait 15s and re-run.')",
])))

# ── CELL 7
nb["cells"].append(code_cell("cell-07", "\n".join([
    "# CELL 7 — Load Quora Dataset (10-30 min)",
    "import httpx, time",
    "",
    "DATASET = 'quora'",
    "r = httpx.post('http://localhost:8000/dataset/load',",
    "               json={'dataset_name': DATASET}, timeout=30)",
    "print('Response:', r.json())",
    "",
    "while True:",
    "    r = httpx.get(f'http://localhost:8000/dataset/status?dataset_name={DATASET}')",
    "    d = r.json()",
    "    status = d.get('status')",
    "    docs = d.get('progress_docs', 0)",
    "    total = d.get('total_docs', '?')",
    "    print(f'  Status: {status:12}  Docs: {docs}/{total}')",
    "    if status == 'ready':",
    "        print(f'Dataset ready! ({total} docs)')",
    "        break",
    "    elif status == 'error':",
    "        print('Error:', d.get('error'))",
    "        break",
    "    time.sleep(20)",
])))

# ── CELL 8
nb["cells"].append(code_cell("cell-08", "\n".join([
    "# CELL 8 — Build Search Indexes (30-60 min, use GPU!)",
    "import httpx, time",
    "",
    "r = httpx.post('http://localhost:8000/index/build',",
    "    json={'dataset_name': 'quora', 'models': ['tfidf', 'bm25', 'word2vec', 'bert']}, timeout=30)",
    "print('Response:', r.json())",
    "",
    "while True:",
    "    r = httpx.get('http://localhost:8000/index/status?dataset_name=quora')",
    "    d = r.json()",
    "    status = d.get('status')",
    "    built = d.get('built_models', [])",
    "    print(f'  Status: {status:12}  Built: {built}')",
    "    if status == 'ready':",
    "        print('All indexes ready:', built)",
    "        break",
    "    elif status == 'error':",
    "        print('Error:', d.get('error'))",
    "        break",
    "    time.sleep(20)",
])))

# ── CELL 9 — LDA
nb["cells"].append(code_cell("cell-09", "\n".join([
    "# CELL 9 — Build LDA Topic Model  *** NEW FEATURE ***",
    "import httpx, time",
    "",
    "print('Building LDA Topic Model (10 topics)...')",
    "r = httpx.post('http://localhost:8000/topics/build?dataset_name=quora&num_topics=10', timeout=30)",
    "print('Response:', r.json())",
    "",
    "while True:",
    "    r = httpx.get('http://localhost:8000/topics/status?dataset_name=quora')",
    "    d = r.json()",
    "    status = d.get('status')",
    "    print(f'  Status: {status}')",
    "    if status == 'ready':",
    "        print('LDA ready!', d.get('num_topics'), 'topics discovered')",
    "        break",
    "    elif status == 'error':",
    "        print('Error:', d.get('error'))",
    "        break",
    "    time.sleep(15)",
])))

# ── CELL 10 — View Topics
nb["cells"].append(code_cell("cell-10", "\n".join([
    "# CELL 10 — View All Topics  *** NEW FEATURE ***",
    "import httpx",
    "",
    "r = httpx.get('http://localhost:8000/topics/all?dataset_name=quora')",
    "data = r.json()",
    "",
    "print(data['num_topics'], 'Topics Discovered in Quora Dataset:')",
    "print()",
    "print(f\"  {'ID':<5} {'Label':<35} {'Top 5 Words':<45} Docs\")",
    "print('  ' + '-' * 90)",
    "",
    "for t in data['topics']:",
    "    words = ', '.join(t['top_words'][:5])",
    "    print(f\"  {t['topic_id']:<5} {t['label']:<35} {words:<45} {t['doc_count']}\")",
])))

# ── CELL 11 — Search with Topics
nb["cells"].append(code_cell("cell-11", "\n".join([
    "# CELL 11 — Search WITH Topic Labels  *** NEW FEATURE ***",
    "import httpx",
    "",
    "QUERY = 'what is machine learning'",
    "",
    "r = httpx.post('http://localhost:8000/search/with-topics', json={",
    "    'query': QUERY, 'dataset': 'quora', 'model': 'bm25',",
    "    'top_k': 5, 'use_refinement': False,",
    "}, timeout=30)",
    "",
    "result = r.json()",
    "print(f\"Query  : {result['query_original']}\")",
    "print(f\"Latency: {result['latency_ms']:.1f}ms\")",
    "print()",
    "",
    "for item in result['results']:",
    "    topic = item.get('topic') or {}",
    "    snippet = (item.get('snippet') or '')[:70].replace('\\n', ' ')",
    "    print(f\"  #{item['rank']}  doc={item['doc_id']}  score={item['score']:.4f}\")",
    "    print(f\"      Topic [{topic.get('topic_id','?')}]: {topic.get('topic_label','unknown')}\")",
    "    words = ', '.join(topic.get('top_words', [])[:4])",
    "    print(f\"      Words: {words}\")",
    "    if snippet: print(f\"      Text : {snippet}...\")",
    "    print()",
])))

# ── CELL 12
nb["cells"].append(code_cell("cell-12", "\n".join([
    "# CELL 12 — Regular Search",
    "import httpx",
    "",
    "r = httpx.post('http://localhost:8000/search', json={",
    "    'query': 'what is machine learning',",
    "    'dataset': 'quora',",
    "    'model': 'bm25',",
    "    'top_k': 10,",
    "    'use_refinement': False,",
    "}, timeout=30)",
    "",
    "result = r.json()",
    "print(f\"Query  : {result['query_original']}\")",
    "print(f\"Model  : {result['model']}\")",
    "print(f\"Latency: {result['latency_ms']:.1f}ms\")",
    "print()",
    "",
    "for item in result['results']:",
    "    snippet = (item.get('snippet') or '')[:80].replace('\\n', ' ')",
    "    print(f\"  #{item['rank']:<3} score={item['score']:.4f}  doc={item['doc_id']}\")",
    "    if snippet: print(f\"       {snippet}...\")",
])))

# ── CELL 13
nb["cells"].append(code_cell("cell-13", "\n".join([
    "# CELL 13 — Compare All 6 Models",
    "import httpx",
    "",
    "QUERY = 'what is machine learning'",
    "print('Query:', QUERY)",
    "print()",
    "print(f\"  {'Model':<22} {'Top Doc':<15} {'Score':<12} Latency\")",
    "print('  ' + '-' * 60)",
    "",
    "for model in ['tfidf', 'bm25', 'word2vec', 'bert', 'hybrid_serial', 'hybrid_parallel']:",
    "    try:",
    "        r = httpx.post('http://localhost:8000/search', json={",
    "            'query': QUERY, 'dataset': 'quora', 'model': model, 'top_k': 1",
    "        }, timeout=60)",
    "        d = r.json()",
    "        top = d['results'][0] if d['results'] else None",
    "        if top:",
    "            print(f\"  {model:<22} {top['doc_id']:<15} {top['score']:<12.4f} {d['latency_ms']:.0f}ms\")",
    "    except Exception as e:",
    "        print(f'  {model:<22} ERROR: {e}')",
])))

# ── CELL 14
nb["cells"].append(code_cell("cell-14", "\n".join([
    "# CELL 14 — Evaluate Models (MAP, nDCG)",
    "import httpx, math",
    "",
    "DATASET = 'quora'",
    "K = 10",
    "NUM_QUERIES = 50",
    "",
    "qrels = httpx.get(f'http://localhost:8001/dataset/qrels?dataset_name={DATASET}', timeout=120).json()['qrels']",
    "qtexts = {q['query_id']: q['original']",
    "          for q in httpx.get(f'http://localhost:8001/dataset/queries?dataset_name={DATASET}&offset=0&limit=500',",
    "                             timeout=60).json()['queries']}",
    "valid = [qid for qid in list(qrels.keys())[:NUM_QUERIES] if qid in qtexts]",
    "print(f'Evaluating {len(valid)} queries...')",
    "",
    "def ap(ranked, rel):",
    "    R = sum(1 for v in rel.values() if v >= 1)",
    "    if not R: return 0.0",
    "    h = s = 0",
    "    for i, d in enumerate(ranked, 1):",
    "        if rel.get(d, 0) >= 1: h += 1; s += h / i",
    "    return s / R",
    "",
    "def ndcg(ranked, rel, k):",
    "    dcg  = sum((2**rel.get(d,0)-1)/math.log2(i+1) for i,d in enumerate(ranked[:k],1) if rel.get(d,0)>0)",
    "    idcg = sum((2**r-1)/math.log2(i+1) for i,r in enumerate(sorted(rel.values(),reverse=True)[:k],1) if r>0)",
    "    return dcg/idcg if idcg else 0.0",
    "",
    "results = {}",
    "for model in ['tfidf', 'bm25', 'word2vec', 'bert']:",
    "    print(f'  Testing {model}...', end=' ', flush=True)",
    "    aps, ns = [], []",
    "    for qid in valid:",
    "        r = httpx.post('http://localhost:8000/search', json={",
    "            'query': qtexts[qid], 'dataset': DATASET, 'model': model,",
    "            'top_k': K, 'use_refinement': False}, timeout=30)",
    "        ranked = [x['doc_id'] for x in r.json().get('results', [])]",
    "        aps.append(ap(ranked, qrels[qid]))",
    "        ns.append(ndcg(ranked, qrels[qid], K))",
    "    n = max(len(aps), 1)",
    "    results[model] = {'map': round(sum(aps)/n, 4), 'ndcg': round(sum(ns)/n, 4)}",
    "    print(f\"MAP={results[model]['map']}  nDCG={results[model]['ndcg']}\")",
    "",
    "print()",
    "print(f\"  {'Model':<18} {'MAP':<12} nDCG@10\")",
    "print('  ' + '-' * 40)",
    "for m in sorted(results, key=lambda x: results[x]['map'], reverse=True):",
    "    print(f\"  {m:<18} {results[m]['map']:<12} {results[m]['ndcg']}\")",
    "best = max(results, key=lambda x: results[x]['map'])",
    "print(f'Best model: {best} (MAP={results[best][\"map\"]})')",
])))

# ── CELL 15
nb["cells"].append(code_cell("cell-15", "\n".join([
    "# CELL 15 — View Logs",
    "import os",
    "",
    "logs = sorted([f for f in os.listdir('/content') if f.startswith('log_') and f.endswith('.txt')])",
    "for log in logs:",
    "    with open(f'/content/{log}') as f:",
    "        lines = f.read().strip().split('\\n')",
    "    recent = lines[-5:]",
    "    has_err = any('error' in l.lower() or 'traceback' in l.lower() for l in recent)",
    "    label = 'ERROR' if has_err else 'OK'",
    "    print(f'\\n[{label}]  {log}')",
    "    print('-' * 50)",
    "    print('\\n'.join(recent[-3:]))",
])))

# ── CELL 16
nb["cells"].append(code_cell("cell-16", "\n".join([
    "# CELL 16 — Save Indexes to Google Drive",
    "from google.colab import drive",
    "import shutil, os",
    "",
    "drive.mount('/content/drive')",
    "",
    "SRC = os.path.normpath(os.path.join(BACKEND_PATH, '..', 'data'))",
    "DST = '/content/drive/MyDrive/IR_Project_indexes'",
    "",
    "if os.path.exists(DST):",
    "    print('Removing old indexes...')",
    "    shutil.rmtree(DST)",
    "",
    "print('Saving to Google Drive...')",
    "shutil.copytree(SRC, DST)",
    "",
    "total_mb = sum(",
    "    os.path.getsize(os.path.join(root, f)) // 1024 // 1024",
    "    for root, dirs, files in os.walk(DST) for f in files)",
    "print(f'Saved! (~{total_mb} MB)')",
    "print('Next session: run Cell 16b!')",
])))

# ── CELL 16b
nb["cells"].append(code_cell("cell-16b", "\n".join([
    "# CELL 16b — Restore Indexes from Drive (use instead of Cells 7+8+9)",
    "from google.colab import drive",
    "import shutil, os",
    "",
    "drive.mount('/content/drive')",
    "",
    "SRC = '/content/drive/MyDrive/IR_Project_indexes'",
    "DST = os.path.normpath(os.path.join(BACKEND_PATH, '..', 'data'))",
    "",
    "if not os.path.exists(SRC):",
    "    print('No saved indexes on Drive. Run Cells 7+8+9 first, then Cell 16.')",
    "else:",
    "    if os.path.exists(DST): shutil.rmtree(DST)",
    "    shutil.copytree(SRC, DST)",
    "    for dataset in os.listdir(DST):",
    "        files = os.listdir(os.path.join(DST, dataset))",
    "        print(f'  Restored {dataset}: {len(files)} files')",
    "    print('Done! Go to Cell 11 to search.')",
])))

# ── SAVE
out = r"C:\Users\n_alb\OneDrive\سطح المكتب\IR_Project_Colab.ipynb"
with open(out, "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f"Notebook saved: {out}")
print(f"Total cells: {len(nb['cells'])}")
